/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.lucasgiavaroti.ui;

import br.com.lucasgiavaroti.dao.DespesaDAO;
import br.com.lucasgiavaroti.model.Categoria;
import br.com.lucasgiavaroti.model.Despesa;
import java.awt.Color;
import java.time.LocalDate;
import java.util.Optional;

/**
 *
 * @author Lucas
 */
public class Alterar extends javax.swing.JFrame {

    /**
     * Creates new form Alterar
     */
    public Alterar() {
        initComponents();
        jlParagrafo.setVisible(false);
        jlValor.setVisible(false);
        jlCategoria.setVisible(false);
        jlDescricao.setVisible(false);
        jlData.setVisible(false);
        jtfDate.setVisible(false);
        jtfDesc.setVisible(false);
        jtfValor.setVisible(false);
        jcbCat.setVisible(false);
        jbVoltar2.setVisible(false);
        jbAlterar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdDespesaNaoEncontrada = new javax.swing.JDialog();
        jlParagrafo1 = new javax.swing.JLabel();
        jlParagrafo2 = new javax.swing.JLabel();
        jbOkDialogo01 = new javax.swing.JButton();
        jdDespesaSucesso = new javax.swing.JDialog();
        jlParagrafo3 = new javax.swing.JLabel();
        jbOkDialogo02 = new javax.swing.JButton();
        jdErro = new javax.swing.JDialog();
        jlParagrafo4 = new javax.swing.JLabel();
        jlParagrafo5 = new javax.swing.JLabel();
        jbOkDialogo03 = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        jlSubTitulo = new javax.swing.JLabel();
        jtfId = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jlParagrafo = new javax.swing.JLabel();
        jlValor = new javax.swing.JLabel();
        jlCategoria = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jlDescricao = new javax.swing.JLabel();
        jtfDate = new javax.swing.JTextField();
        jtfDesc = new javax.swing.JTextField();
        jtfValor = new javax.swing.JTextField();
        jcbCat = new javax.swing.JComboBox<>();
        jbVoltar2 = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();

        jdDespesaNaoEncontrada.setTitle("Despesa não encontrada");
        jdDespesaNaoEncontrada.setMaximumSize(new java.awt.Dimension(400, 300));
        jdDespesaNaoEncontrada.setMinimumSize(new java.awt.Dimension(400, 300));

        jlParagrafo1.setForeground(new java.awt.Color(204, 204, 0));
        jlParagrafo1.setText("Despesa não encontrada!");

        jlParagrafo2.setText("Por favor, verifique o ID e digite novamente.");

        jbOkDialogo01.setText("Ok");
        jbOkDialogo01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkDialogo01ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdDespesaNaoEncontradaLayout = new javax.swing.GroupLayout(jdDespesaNaoEncontrada.getContentPane());
        jdDespesaNaoEncontrada.getContentPane().setLayout(jdDespesaNaoEncontradaLayout);
        jdDespesaNaoEncontradaLayout.setHorizontalGroup(
            jdDespesaNaoEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdDespesaNaoEncontradaLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(jdDespesaNaoEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdDespesaNaoEncontradaLayout.createSequentialGroup()
                        .addComponent(jlParagrafo1)
                        .addGap(100, 100, 100))
                    .addComponent(jlParagrafo2))
                .addGap(86, 86, 86))
            .addGroup(jdDespesaNaoEncontradaLayout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jbOkDialogo01, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jdDespesaNaoEncontradaLayout.setVerticalGroup(
            jdDespesaNaoEncontradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdDespesaNaoEncontradaLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jlParagrafo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlParagrafo2)
                .addGap(18, 18, 18)
                .addComponent(jbOkDialogo01)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        jdDespesaSucesso.setTitle("Despesa alterada");
        jdDespesaSucesso.setMaximumSize(new java.awt.Dimension(400, 300));
        jdDespesaSucesso.setMinimumSize(new java.awt.Dimension(400, 300));

        jlParagrafo3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlParagrafo3.setForeground(new java.awt.Color(102, 204, 0));
        jlParagrafo3.setText("Despesa Alterada com Sucesso!");

        jbOkDialogo02.setText("Ok");
        jbOkDialogo02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkDialogo02ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdDespesaSucessoLayout = new javax.swing.GroupLayout(jdDespesaSucesso.getContentPane());
        jdDespesaSucesso.getContentPane().setLayout(jdDespesaSucessoLayout);
        jdDespesaSucessoLayout.setHorizontalGroup(
            jdDespesaSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdDespesaSucessoLayout.createSequentialGroup()
                .addGroup(jdDespesaSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdDespesaSucessoLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jbOkDialogo02, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jdDespesaSucessoLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jlParagrafo3)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jdDespesaSucessoLayout.setVerticalGroup(
            jdDespesaSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdDespesaSucessoLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jlParagrafo3)
                .addGap(28, 28, 28)
                .addComponent(jbOkDialogo02)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        jdErro.setTitle("Despesa não alterada");
        jdErro.setMaximumSize(new java.awt.Dimension(400, 300));
        jdErro.setPreferredSize(new java.awt.Dimension(400, 300));

        jlParagrafo4.setForeground(new java.awt.Color(204, 0, 0));
        jlParagrafo4.setText("A Despesa NÃO foi alterada com sucesso :(");

        jlParagrafo5.setText("Por favor, verifique os campos e tente novamente.");

        jbOkDialogo03.setText("Ok");
        jbOkDialogo03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkDialogo03ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdErroLayout = new javax.swing.GroupLayout(jdErro.getContentPane());
        jdErro.getContentPane().setLayout(jdErroLayout);
        jdErroLayout.setHorizontalGroup(
            jdErroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdErroLayout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jbOkDialogo03)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jdErroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jdErroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlParagrafo4)
                    .addComponent(jlParagrafo5))
                .addGap(60, 60, 60))
        );
        jdErroLayout.setVerticalGroup(
            jdErroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdErroLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jlParagrafo4)
                .addGap(18, 18, 18)
                .addComponent(jlParagrafo5)
                .addGap(27, 27, 27)
                .addComponent(jbOkDialogo03)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alterar");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jlTitulo.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jlTitulo.setText("Alterar Despesa");

        jlSubTitulo.setText("Digite o ID da despesa que deseja alterar:");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jlParagrafo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlParagrafo.setText("Por favor, altere os campos com os novos dados: ");

        jlValor.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlValor.setText("Valor: (R$)");

        jlCategoria.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlCategoria.setText("Categoria: ");

        jlData.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlData.setText("Data:");

        jlDescricao.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jlDescricao.setText("Descrição: ");

        jcbCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MORADIA", "SAUDE", "EDUCACAO", "ALIMENTACAO", "TRANSPORTE", "OUTROS" }));

        jbVoltar2.setText("Voltar");
        jbVoltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltar2ActionPerformed(evt);
            }
        });

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSubTitulo)
                    .addComponent(jlTitulo)
                    .addComponent(jlParagrafo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlCategoria)
                            .addComponent(jlDescricao)
                            .addComponent(jtfDesc, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(jcbCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlValor)
                            .addComponent(jlData)
                            .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbVoltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jtfId, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jbBuscar)
                            .addGap(18, 18, 18)
                            .addComponent(jbVoltar))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jlTitulo)
                .addGap(24, 24, 24)
                .addComponent(jlSubTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtfId, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBuscar)
                    .addComponent(jbVoltar))
                .addGap(48, 48, 48)
                .addComponent(jlParagrafo)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlValor)
                    .addComponent(jlDescricao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfValor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCategoria)
                    .addComponent(jlData))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCat, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVoltar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        DespesaDAO dao = new DespesaDAO();
        Optional<Despesa> despesaOptional = dao.findById(Long.valueOf(jtfId.getText()));
        
        if(despesaOptional.isEmpty()){
            jdDespesaNaoEncontrada.setVisible(true);
            jdDespesaNaoEncontrada.setLocationRelativeTo(null);
        }else{
            jbVoltar.setVisible(false);
            jlParagrafo.setVisible(true);
            
            jlValor.setVisible(true);
            jlCategoria.setVisible(true);
            jlDescricao.setVisible(true);
            jlData.setVisible(true);
            
            jtfDate.setText(String.valueOf(despesaOptional.get().getData()));
            jtfDate.setVisible(true);
            
            jtfDesc.setText(despesaOptional.get().getDescricao());
            jtfDesc.setVisible(true);
            
            jtfValor.setText(String.valueOf(despesaOptional.get().getValor()));
            jtfValor.setVisible(true);
            
            jcbCat.setSelectedIndex(selectComboBox(String.valueOf(despesaOptional.get().getCategoria())));
            jcbCat.setVisible(true);
            
            jbVoltar2.setVisible(true);
            jbAlterar.setVisible(true);
            
        }
        
    }//GEN-LAST:event_jbBuscarActionPerformed

    private int selectComboBox (String categoria){
        
        int index = 0;
        
        if(categoria.equalsIgnoreCase("SAUDE")){
            index = 1;
        }else if(categoria.equalsIgnoreCase("EDUCACAO")){
            index = 2;
        }else if(categoria.equalsIgnoreCase("ALIMENTACAO")){
            index = 3;
        }else if(categoria.equalsIgnoreCase("TRANSPORTE")){
            index = 4;
        }else if(categoria.equalsIgnoreCase("OUTROS")){
            index = 5;
        }
        
        return index;
    }
    
    private void jbOkDialogo01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkDialogo01ActionPerformed
        // TODO add your handling code here:
        jdDespesaNaoEncontrada.dispose();
        jlParagrafo.setVisible(false);
        jlValor.setVisible(false);
        jlCategoria.setVisible(false);
        jlDescricao.setVisible(false);
        jlData.setVisible(false);
        jtfDate.setVisible(false);
        jtfDesc.setVisible(false);
        jtfValor.setVisible(false);
        jcbCat.setVisible(false);
        jbVoltar2.setVisible(false);
        jbAlterar.setVisible(false);
        jbVoltar.setVisible(true);
        jtfId.setText("");
    }//GEN-LAST:event_jbOkDialogo01ActionPerformed

    private void jbVoltar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltar2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbVoltar2ActionPerformed

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        // TODO add your handling code here:
        
         DespesaDAO dao = new DespesaDAO();
        
         Optional<Despesa> despesaOptional = dao.findById(Long.valueOf(jtfId.getText()));
        
         despesaOptional.get().setDescricao(jtfDesc.getText());
         despesaOptional.get().setValor(Double.valueOf(jtfValor.getText()));
         despesaOptional.get().setCategoria(Categoria.valueOf(jcbCat.getSelectedItem().toString()));
         despesaOptional.get().setData(LocalDate.parse(jtfDate.getText()));
        
          try{
                dao.update(despesaOptional.get());
                jdDespesaSucesso.setLocationRelativeTo(null);
                jdDespesaSucesso.setVisible(true);
         }catch(RuntimeException e){
                jdErro.setLocationRelativeTo(null);
                jdErro.setVisible(true);
            }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbOkDialogo02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkDialogo02ActionPerformed
        // TODO add your handling code here:
        jdDespesaSucesso.dispose();
        jlParagrafo.setVisible(false);
        jlValor.setVisible(false);
        jlCategoria.setVisible(false);
        jlDescricao.setVisible(false);
        jlData.setVisible(false);
        jtfDate.setVisible(false);
        jtfDesc.setVisible(false);
        jtfValor.setVisible(false);
        jcbCat.setVisible(false);
        jbVoltar2.setVisible(false);
        jbAlterar.setVisible(false);
        jbVoltar.setVisible(true);
        jtfId.setText("");
    }//GEN-LAST:event_jbOkDialogo02ActionPerformed

    private void jbOkDialogo03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkDialogo03ActionPerformed
        // TODO add your handling code here:
        jdErro.dispose();
    }//GEN-LAST:event_jbOkDialogo03ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alterar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Alterar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbOkDialogo01;
    private javax.swing.JButton jbOkDialogo02;
    private javax.swing.JButton jbOkDialogo03;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JButton jbVoltar2;
    private javax.swing.JComboBox<String> jcbCat;
    private javax.swing.JDialog jdDespesaNaoEncontrada;
    private javax.swing.JDialog jdDespesaSucesso;
    private javax.swing.JDialog jdErro;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlParagrafo;
    private javax.swing.JLabel jlParagrafo1;
    private javax.swing.JLabel jlParagrafo2;
    private javax.swing.JLabel jlParagrafo3;
    private javax.swing.JLabel jlParagrafo4;
    private javax.swing.JLabel jlParagrafo5;
    private javax.swing.JLabel jlSubTitulo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlValor;
    private javax.swing.JTextField jtfDate;
    private javax.swing.JTextField jtfDesc;
    private javax.swing.JTextField jtfId;
    private javax.swing.JTextField jtfValor;
    // End of variables declaration//GEN-END:variables
}
