/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.lucasgiavaroti.ui;

import br.com.lucasgiavaroti.dao.DespesaDAO;
import br.com.lucasgiavaroti.model.Categoria;
import br.com.lucasgiavaroti.model.Despesa;
import java.awt.Color;
import java.time.LocalDate;

/**
 *
 * @author Lucas
 */
public class Cadastrar extends javax.swing.JFrame {

    /**
     * Creates new form Cadastrar
     */
    public Cadastrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdCadastroSucesso = new javax.swing.JDialog();
        jlSucesso = new javax.swing.JLabel();
        jbOkCadastro = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        jlDescricao = new javax.swing.JLabel();
        jlData = new javax.swing.JLabel();
        jlCategoria = new javax.swing.JLabel();
        jcbCat = new javax.swing.JComboBox<>();
        jtDesc = new javax.swing.JTextField();
        jlValor = new javax.swing.JLabel();
        jbCadastrar = new javax.swing.JButton();
        jbVoltar = new javax.swing.JButton();
        jtDate = new javax.swing.JTextField();
        jtVlr = new javax.swing.JTextField();

        jdCadastroSucesso.setTitle("Sucesso");
        jdCadastroSucesso.setMinimumSize(new java.awt.Dimension(400, 300));
        jdCadastroSucesso.setResizable(false);

        jlSucesso.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jlSucesso.setForeground(new java.awt.Color(51, 204, 0));
        jlSucesso.setText("Despesa Cadastrada com Sucesso!");

        jbOkCadastro.setText("Ok");
        jbOkCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbOkCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdCadastroSucessoLayout = new javax.swing.GroupLayout(jdCadastroSucesso.getContentPane());
        jdCadastroSucesso.getContentPane().setLayout(jdCadastroSucessoLayout);
        jdCadastroSucessoLayout.setHorizontalGroup(
            jdCadastroSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCadastroSucessoLayout.createSequentialGroup()
                .addGroup(jdCadastroSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jdCadastroSucessoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jlSucesso))
                    .addGroup(jdCadastroSucessoLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jbOkCadastro)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jdCadastroSucessoLayout.setVerticalGroup(
            jdCadastroSucessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdCadastroSucessoLayout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jlSucesso)
                .addGap(28, 28, 28)
                .addComponent(jbOkCadastro)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastar ");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jlTitulo.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jlTitulo.setText("Cadastrar Despesa");

        jlDescricao.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jlDescricao.setText("Descrição:");

        jlData.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jlData.setLabelFor(jtVlr);
        jlData.setText("Data:");

        jlCategoria.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jlCategoria.setLabelFor(jcbCat);
        jlCategoria.setText("Categoria:");

        jcbCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MORADIA", "SAUDE", "EDUCACAO", "ALIMENTACAO", "TRANSPORTE", "OUTROS" }));

        jtDesc.setToolTipText("Descrição da despesa");

        jlValor.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        jlValor.setText("Valor: (R$)");

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbVoltar.setText("Voltar");
        jbVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarActionPerformed(evt);
            }
        });

        jtDate.setForeground(java.awt.Color.gray);
        jtDate.setText("Ex: 2024-12-31");
        jtDate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtDateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtDateFocusLost(evt);
            }
        });

        jtVlr.setForeground(java.awt.Color.gray);
        jtVlr.setText("Ex: 49.99");
        jtVlr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtVlrFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtVlrFocusLost(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlCategoria)
                            .addComponent(jlDescricao)
                            .addComponent(jlTitulo)
                            .addComponent(jcbCat, 0, 241, Short.MAX_VALUE)
                            .addComponent(jtDesc))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlData)
                            .addComponent(jlValor)
                            .addComponent(jtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jtVlr)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jlTitulo)
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDescricao)
                    .addComponent(jlValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtVlr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlData, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlCategoria))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtDate))
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(61, 61, 61))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarActionPerformed
        // TODO add your handling code here:
        retornarMenu();
    }//GEN-LAST:event_jbVoltarActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        // TODO add your handling code here:
        DespesaDAO dao = new DespesaDAO();
        Despesa despesa = new Despesa();
        
        despesa.setDescricao(jtDesc.getText());
        
        double valor = Double.parseDouble(jtVlr.getText());
        despesa.setValor(valor);
        
        despesa.setCategoria(Categoria.valueOf(jcbCat.getSelectedItem().toString()));
        
        despesa.setData(LocalDate.parse(jtDate.getText()));
        
         try{
             dao.save(despesa);
             jdCadastroSucesso.setLocationRelativeTo(null);
             jdCadastroSucesso.setVisible(true);
         }catch(RuntimeException e){
             System.out.print(e);
         }
        
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jtDateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDateFocusGained
        // TODO add your handling code here:
        jtDate.setText("");
        jtDate.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtDateFocusGained

    private void jtDateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtDateFocusLost
        // TODO add your handling code here:
       if(jtDate.getText().isEmpty()){
         jtDate.setText("Ex: 2024-12-31");
         jtDate.setForeground(Color.gray);
       }
    }//GEN-LAST:event_jtDateFocusLost

    private void jtVlrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtVlrFocusGained
        // TODO add your handling code here:
        jtVlr.setText("");
        jtVlr.setForeground(Color.BLACK);
    }//GEN-LAST:event_jtVlrFocusGained

    private void jtVlrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtVlrFocusLost
        // TODO add your handling code here:
        if(jtVlr.getText().isEmpty()){
            jtVlr.setText("Ex: 49.99");
        jtVlr.setForeground(Color.gray);
       }
    }//GEN-LAST:event_jtVlrFocusLost

    private void jbOkCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbOkCadastroActionPerformed
        // TODO add your handling code here:
        jdCadastroSucesso.dispose();
    }//GEN-LAST:event_jbOkCadastroActionPerformed
    
     private void retornarMenu() {
        this.dispose();        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbOkCadastro;
    private javax.swing.JButton jbVoltar;
    private javax.swing.JComboBox<String> jcbCat;
    private javax.swing.JDialog jdCadastroSucesso;
    private javax.swing.JLabel jlCategoria;
    private javax.swing.JLabel jlData;
    private javax.swing.JLabel jlDescricao;
    private javax.swing.JLabel jlSucesso;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlValor;
    private javax.swing.JTextField jtDate;
    private javax.swing.JTextField jtDesc;
    private javax.swing.JTextField jtVlr;
    // End of variables declaration//GEN-END:variables

}
